### ISSUE TITLE
Can't click links in irccloud

### ISSUE THREAD

**Issue by popey** [snapcrafters/irccloud-desktop#1]
I have installed irccloud-desktop on my 16.04 laptop, but when I click links in irc channels, nothing happens. I have snapd-xdg-open installed.

```
alan@hal:~$ snap version
snap    2.27.6
snapd   2.27.6
series  16
ubuntu  16.04
kernel  4.10.0-33-generic
```

```
alan@hal:~$ snap info irccloud-desktop
name:      irccloud-desktop
summary:   "IRCCloud Desktop App"
publisher: diddledan
description: |
  IRCCloud Desktop App
  
snap-id: GzRid1k9bGro72ivGFJWluviBgwnFSCO
commands:
  - irccloud-desktop
tracking:    stable
installed:   0.3.0 (1) 114MB -
refreshed:   2017-08-17 14:36:08 +0100 BST
channels:              
  stable:    0.3.0 (1) 114MB -
  candidate: 0.3.0 (1) 114MB -
  beta:      0.3.0 (1) 114MB -
  edge:      0.3.0 (5) 114MB -

```

**Comment by lucyllewy** [comment]
this is probably due to https://forum.snapcraft.io/t/xdg-open-regression/2085

Or not, I just tested on a fresh core which allows xdg-open in corebird, and it still fails here... I'm unsure then..

**Comment by lucyllewy** [comment]
This is the error as reported by irccloud itself:

```text
Error org.freedesktop.DBus.Error.ServiceUnknown: The name io.snapcraft.Launcher was not provided by any .service files
Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonial.SafeLauncher was not provided by any .service files
```

**Comment by lucyllewy** [comment]
running the following command once core is on `16-2.27.6` fixes it for me:

```bash
sudo /usr/lib/snapd/snap-discard-ns irccloud-desktop
```

**Comment by lucyllewy** [comment]
I've posted about this in the forum: https://forum.snapcraft.io/t/core-updates-fail-to-reset-other-snaps-namespace/2190

**Comment by popey** [comment]
Seems to be working here now, magically.

**Comment by lucyllewy** [comment]
It's working now because the upstream snapd changes are now released to stable.
