### ISSUE TITLE
Not using system cursor or menu theme

### ISSUE THREAD

**Issue by Deraen** [snapcrafters/irccloud-desktop#10]
Ubuntu 18.04

Both menu theme and cursor work when using official IRCCloud desktop deb package.

IRCCloud context menu:
![image](https://user-images.githubusercontent.com/648087/41546168-a1354692-7325-11e8-9cdd-cbee773432a9.png)

System context menu from Chrome:
![image](https://user-images.githubusercontent.com/648087/41546255-d74e4f44-7325-11e8-8e8c-663ea742def1.png)

Also cursor over IRCCloud doesn't seem to use system cursor theme.

**Comment by Deraen** [comment]
I just noticed that the latest change switches to gtk3, and switching to edge build fixes the menu theme. 

Cursor is still wrong.

**Comment by popey** [comment]
Thanks for the issue, but this snap is no longer maintained. The upstream developer has a new, better, well-maintained snap over at https://snapcraft.io/irccloud
Thanks.
