### ISSUE TITLE
Application starts to be unresponding and draining lots of memory when selecting File > Jump to

### ISSUE THREAD

**Issue by brlin-tw** [snapcrafters/irccloud-desktop#17]
As title.

**Comment by lucyllewy** [comment]
yes, it hangs here too. I don't see any log messages or AppArmor conflicts, so I'm not sure whether this is a bug in the snap or in IRCCloud desktop directly.

**Comment by popey** [comment]
Thanks for the issue, but this snap is no longer maintained. The upstream developer has a new, better, well-maintained snap over at https://snapcraft.io/irccloud
Thanks.
