### ISSUE TITLE
Please update to 0.5.0

### ISSUE THREAD

**Issue by popey** [snapcrafters/irccloud-desktop#2]
New version of IRC Cloud Desktop was released a couple of days ago... https://github.com/irccloud/irccloud-desktop/releases

**Comment by lucyllewy** [comment]
There's a blocker on updating this version in upstream dependencies which use chosen causing irccloud to be killed by seccomp

**Comment by lucyllewy** [comment]
That should read Chown not chosen. Silly spilling chucker caught me.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/irccloud-desktop/commit/f46fa412d588c6e1b4b51ba29654faeb9e157afa. ircclod-desktop 0.5.1 is now in the stable channel.
