### ISSUE TITLE
Upstream build and publishing

### ISSUE THREAD

**Issue by jwheare** [snapcrafters/irccloud-desktop#22]
Hi, I maintain the upstream https://github.com/irccloud/irccloud-desktop electron app. In the past, I've tried to build snaps directly from upstream but have had a lot of issues. Recently electron-builder has come a long way to add better snap support so I've tried again and it seems to have worked

I've got snap file creation and deploying to the snapcraft store working [using the travis CI docs](https://docs.travis-ci.com/user/deployment/snaps):

https://snapcraft.io/irccloud

A few questions:

* Can anyone on this project help test our build? I'm running macOS so it's not straightforward.
* What changes should be made to our build for it to be a better snap citizen. I notice a heap of options in the yaml for this repository that I don't understand. electron-builder sets some defaults and should populate stuff from our package.json but I'm sure there's a bunch missing. Ideally, it's all stuff I can add via configuration https://www.electron.build/configuration/snap
* Once this is in a better state with a stable release, is there a way to redirect users of snapcrafters/irccloud-desktop to our upstream build?

**Comment by jwheare** [comment]
I've opened an issue on our end to track blockers for this: https://github.com/irccloud/irccloud-desktop/issues/142

**Comment by lucyllewy** [comment]
Hi James,

Regarding the extra stuff in the `snapcraft.yaml` I believe most of it will be handled automatically by your usage of `electron-builder`. I think you only really need to worry about which interfaces you want to plug when looking at our yaml. For reference the plugs we currently define are:

```yaml
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - opengl
      - pulseaudio
      - unity7
      - x11
```

I believe `mount-observe` is just to squash a denial message but isn't necessary to run the app. I think that `x11`, `unity7`, `desktop` and `desktop-legacy` should be added automatically by `electron-builder` but can't swear to it :-) `network` and `network-bind` should be fairly obvious. `pulseaudio` is for inline video playback with audio, and `opengl` seems to be required by electron, but again I think `electron-builder` might handle that automatically.

We also define the `gnome-3-28-1804` content interface along with theme-related interfaces. These aren't strictly necessary, and are a way to allow us to reduce the size of the final snap by offloading common-to-many-snaps libraries and themes to a series of shared snaps.

**Comment by jwheare** [comment]
Thanks Dan,

The electron-builder default plugs list matches yours, except for not including `mount-observe` and `network-bind`. Can you provide more details on the denial message and what network-bind might be needed for? I'm not 100% sure, but I don't think our app does any network binding, just outbound connections.

Happy to add the gnome3 stuff, but not sure how to do that with config at the nesting level used in your snapcraft.yaml.

**Comment by lucyllewy** [comment]
It looks like the denial that `mount-observe` squashes is attempted read access to `/etc/fstab` when opening the file browser. This is a common message and doesn't impact the usability of the file browser, so you'll probably be fine not adding `mount-observe`.

```plain
Jul 22 09:25:04 ubuntu-desktop kernel: [294265.416335] audit: type=1400 audit(1563783904.265:1208): apparmor="DENIED" operation="open" profile="snap.irccloud.irccloud" name="/etc/fstab" pid=26286 comm="irccloud" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

**Comment by lucyllewy** [comment]
I think `network-bind` might have been added unnecessarily. I can't see any denials with a quick test with it disconnected.

**Comment by jwheare** [comment]
Re: redirecting users to the official snap, this was discussed in IRC and "merging" on the store isn't possible as such. However, the consensus was that the snapcrafters snap could be updated to be a placeholder app that just politely prompts users to install the official snap instead. This was apparently the process used successfully for the vscode/code snap.

**Comment by jwheare** [comment]
Our primary upstream blocker for an official snap release was fixed (permissions error on config saves) and the latest release on the edge channel is ready for testing https://snapcraft.io/irccloud

If people could test that we can push this forward.

**Comment by lucyllewy** [comment]
Sorry about the late reply.. it all seems to be working fine for me, using edge now :-)

**Comment by anonymouse64** [comment]
Works great for me too

**Comment by jwheare** [comment]
0.14.0 is now released on the stable channel.

**Comment by popey** [comment]
This is now done. The following dialog appears every time irccloud-desktop is launched.

![Screenshot from 2020-02-24 13-31-48](https://user-images.githubusercontent.com/1841272/75156458-18779100-570a-11ea-81db-1d8c36144ff3.png)

The irccloud-desktop snap is now unlisted, and the description changed. I'll close all issues and archive this repo.

Thanks @jwheare !
