### ISSUE TITLE
Error on exit

### ISSUE THREAD

**Issue by smehrbrodt** [snapcrafters/irccloud-desktop#23]
Every time I exit the IRCCloud window, I get a message saying "An unexpected error occurred. The error has been logged."

Where can I find the log files?

![Bildschirmfoto von 2019-10-08 08-52-45](https://user-images.githubusercontent.com/3502738/66373530-1ace8e00-e9a9-11e9-990d-09fba1591130.png)

**Comment by popey** [comment]
Thanks for the issue, but this snap is no longer maintained. The upstream developer has a new, better, well-maintained snap over at https://snapcraft.io/irccloud
Thanks.
