### ISSUE TITLE
irccloud-desktop hangs on startup

### ISSUE THREAD

**Issue by Lukewh** [snapcrafters/irccloud-desktop#8]
Running `irccloud-desktop` hangs with the following:

```
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
[11:16:30.245] [debug] setupConfig
```

OS: Solus
`snap info irccloud`:
```
name:      irccloud-desktop
summary:   IRCCloud Desktop App
publisher: snapcrafters
contact:   https://github.com/snapcrafters/irccloud-desktop/issues
description: |
  IRCCloud Desktop App
snap-id: GzRid1k9bGro72ivGFJWluviBgwnFSCO
commands:
  - irccloud-desktop
tracking:    stable
installed:   0.6.0 (41) 130MB -
refreshed:   2018-04-05 15:44:20 +0100 BST
channels:               
  stable:    0.6.0 (41) 130MB -
  candidate: 0.6.0 (41) 130MB -
  beta:      0.6.0 (41) 130MB -
  edge:      0.6.0 (41) 130MB -
```

**Note** This is probably the first time I've restarted my laptop (and irccloud) since the last refresh.

**Comment by popey** [comment]
Sorry about this. Can you temporarily try `snap refresh core --candidate`? If that works, once snapd 2.32.3 is published in stable, you'll want to `snap refresh core --stable`

**Comment by Lukewh** [comment]
Same problem unfortunately

**Comment by Lukewh** [comment]
Related https://forum.snapcraft.io/t/could-not-find-any-font-error-on-solus-fedora/3251 ?

**Comment by popey** [comment]
Is this still happening with the latest build of irccloud-desktop (0.7.1) which is in edge, and on its way to stable.

**Comment by popey** [comment]
Thanks for the issue, but this snap is no longer maintained. The upstream developer has a new, better, well-maintained snap over at https://snapcraft.io/irccloud
Thanks.
